# Generated by Django 4.1.5 on 2024-05-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_expense_exact_amounts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="exact_amounts",
            field=models.JSONField(default=dict),
        ),
    ]
